// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0W0FQtEcRJx3YtLutO1ZUDTnEaL0H6BM',
    appId: '1:916869031451:web:383302ccb0e29b4b53fabe',
    messagingSenderId: '916869031451',
    projectId: 'healthroutine-unit-2026',
    authDomain: 'healthroutine-unit-2026.firebaseapp.com',
    storageBucket: 'healthroutine-unit-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQtNZ5hL7UTpGo_vex28n3dibaKeha4pQ',
    appId: '1:916869031451:ios:f4bca8cbc447b17e53fabe',
    messagingSenderId: '916869031451',
    projectId: 'healthroutine-unit-2026',
    storageBucket: 'healthroutine-unit-2026.firebasestorage.app',
    iosClientId: '916869031451-n2skd9kmdf9irnfcqaj8om7g38l7flqt.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthroutine',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzfSqLXz1rbrV9MKwn33R9YyaIAXI2I-o',
    appId: '1:916869031451:android:465b06199eb8a95353fabe',
    messagingSenderId: '916869031451',
    projectId: 'healthroutine-unit-2026',
    storageBucket: 'healthroutine-unit-2026.firebasestorage.app',
  );
}
